### PR TITLE
Config Change for RGW Multipart Upload

### PR DESCRIPTION
**Pull request by abhidixit**
Change Min part size for Multipart Upload as per the requirement:
https://bugs.launchpad.net/jio/+bug/1457827
Default value for Min part size limit for Multipart Upload is 5 MB. This is changed to 1 MB as per requirement.

### CODE REVIEW

**Comment by theanalyst** [comment]
Wouldn't this be better placed in `manifests/conf/radosgw.pp` say as `client.radosgw.gateway` rather than under [global] section?

**Comment by abhidixit** [comment]
@theanalyst seems so. done in radosgw.pp only. Initial change was to just check propagation of any conf value.

**Comment by abhidixit** [comment]
Please merge this.
Change Min part size for Multipart Upload as per the requirement:
https://bugs.launchpad.net/jio/+bug/1457827
Default value for Min part size limit for Multipart Upload is 5 MB. This is changed to 1 MB as per requirement.
This is tested via repo change in PR https://github.com/JioCloud/puppet-rjil/pull/645
Build 1599. http://jiocloud.rustedhalo.com:8080/job/puppet-rjil-gate/1599/

**Comment by theanalyst** [comment]
ah ok.. hadn't noted the new commit for moving into radosgw.pp. Fine then

**Comment by anshprat** [comment]
builds passing, merging as requested.

**Pull request merged**
